Перевод на Kotlin списка контактов
yuhnin-m/Android-Lessons pull request #12
Opened 2020-08-26 14:07 UTC by yuhnin-m

Переведено с Java на Kotlin : 
 - Фрагмент
 - Презентер
 - Вью
 - Адаптер для списка контактов
 - Репозиторий для получения списка контактов из ContentResolver'a 
 - Модель
 - Маппер из сущности в модель

2020-08-27 10:27 UTC, RomanMDev requested changes

2020-08-27 10:27 UTC, ghost commented on core/src/main/java/com/a65apps/core/entities/Contact.java
> + * ����� �������� ���������� ����������.
Надо вернуть обратно

2020-08-27 10:27 UTC, ghost commented on library/build.gradle
> +    //kapt "com.google.dagger:dagger-compiler:$dagger_ver"
Удалить

2020-08-27 10:27 UTC, ghost commented on library/build.gradle
> +
лишняя строка

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/mapper/PersonModelCompactDataMapper.kt
> +        return PersonModelCompact(
В таких мелких функциях фигурные скобки можно заменять на `=`. и в таком случае `return` будет не нужен. Также, чтобы не писать `person.a, person.b ` Можно использовать `with(person){ a, b}`.

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/mapper/PersonModelCompactDataMapper.kt
> +        return PersonModelCompact(
Когда много аргументов в конструкторе, методе, то лучше использовать именованные аргументы для удобочитаемости https://kotlinlang.org/docs/reference/functions.html#named-arguments

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/mapper/PersonModelCompactDataMapper.kt
> +    fun transform(personCollection: List<Person>?): List<PersonModelCompact>?{
Точно nullable должны быть? Может не вызывать метод совсем если список null ?

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/mapper/PersonModelCompactDataMapper.kt
> +        if (personCollection != null && !personCollection.isEmpty()) {
`isNotEmpty()`

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonListPresenter.kt
> +    private var compositeDisposable: CompositeDisposable = CompositeDisposable();
Этот и выше `val`

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonListPresenter.kt
> +                        .doOnSubscribe { x: Disposable? -> viewState.showProgressBar() }
Тут переменная `x` никак не используется. Да и когда только одна переменная в лямбде стоит ее именовать либо для удобочитаемости, либо когда `it` начинают друг друга перекрывать. Также тип переменной можно не указывать.

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonListPresenter.kt
> +                                viewState.hideProgressBar()
Т.к. `hideProgressBar()` используется здесь и в `onError()`. то можно вынести его в метод `doOnTerminate/doFinally` (почитай разницу между ними)

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonListPresenter.kt
> +                            viewState.fetchError(it.message?:"asdas")
Нормальная обработка отсутствия текста

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +class PersonListRepositoryFromSystem(val context: Context): PersonListRepository {
private val

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +        if (!searchString.isNullOrEmpty()) {
`searchString` судя по сигнатуре метода notnull. Поэтому здесь можно просто isNotEmpty(). Студия должна выделять такой варнинг

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +        var personList = mutableListOf<Person>()
val

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +        var cursor: Cursor?
Здесь тоже Val, т.к. инициализация происходит один раз

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +            if (cursor != null) {
`?.let`

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +            if (cursor != null) {
Для классов имплементящих интерфейс `Closeable` (Cursor) в котлине есть экстеншен функция `use` https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html которая сама закрывает источник

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
> +                    try {
вместо try удобно использовать `runCatching`. Щас не надо править

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/adapters/PersonListAdapter.kt
> +class PersonListAdapter(val clickedListener: OnPersonClickedListener): ListAdapter<PersonModelCompact,
`OnPersonClickedListener` надо заменить на лямбду https://kotlinlang.org/docs/reference/lambdas.html#higher-order-functions-and-lambdas

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/adapters/PersonListAdapter.kt
> +            RecyclerView.ViewHolder(itemView), View.OnClickListener {
Сделай так, чтобы синтетики можно было использовать в этом ViewHolder.  Почему текущий вариант плох и как сделать нормально( Начиная с раздела "Восстанавливаем views из другого view") https://medium.com/nuances-of-programming/kotlin-android-extensions-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5-%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-42ad43b029d7

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        searchView.queryHint = resources.getString(R.string.action_search)
`with`

2020-08-27 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        if (personList != null) {
`?.let`

2020-08-27 10:27 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        progressbarLoadPersons.visibility = View.GONE
https://developer.android.com/kotlin/ktx/extensions-list

2020-08-27 11:21 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/mapper/PersonModelCompactDataMapper.kt
> +    fun transform(personCollection: List<Person>?): List<PersonModelCompact>?{
Исправил

2020-08-27 11:21 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/mapper/PersonModelCompactDataMapper.kt
> +        return PersonModelCompact(
Исправил

2020-08-27 11:21 UTC, yuhnin-m commented on library/build.gradle
> +
Исправил

2020-08-27 11:21 UTC, yuhnin-m commented on library/build.gradle
> +    //kapt "com.google.dagger:dagger-compiler:$dagger_ver"
Исправил

2020-08-27 11:27 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        searchView.queryHint = resources.getString(R.string.action_search)
Исправил

2020-08-27 11:27 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        if (personList != null) {
Переделал

2020-08-27 11:35 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/adapters/PersonListAdapter.kt
> +            RecyclerView.ViewHolder(itemView), View.OnClickListener {
Почему плохо - понял. Мне нужно включить

2020-08-27 16:35 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/adapters/PersonListAdapter.kt
> +            RecyclerView.ViewHolder(itemView), View.OnClickListener {
Исправил

2020-08-27 19:56 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/adapters/PersonListAdapter.kt
> +            override val containerView: View)
продублировал второй раз вью. `itemVuew` можно было просто переименовать, поставить `override` и не объявлять второй раз ее

2020-08-27 19:56 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +            setLayoutManager(LinearLayoutManager(activity))
`layoutManager =`

2020-08-27 19:56 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        with(view.recyclerviewPersonList) {
`view.` надо убрать. В данном случае с ним не кешируется вью

2020-08-27 19:56 UTC, RomanMDev commented on core/src/main/java/com/a65apps/core/entities/Contact.java
> + * ����� �������� ���������� ����������.
TODO короче

2020-08-27 19:58 UTC, RomanMDev requested changes

2020-08-27 19:58 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        Toast.makeText(requireContext(), errorMessage, Toast.LENGTH_SHORT)
`.show()` у тоста не вызвал

2020-08-27 20:33 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        Toast.makeText(requireContext(), errorMessage, Toast.LENGTH_SHORT)
Исправил

2020-08-27 20:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        with(view.recyclerviewPersonList) {
Проглядел, исправил

2020-08-27 20:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +            setLayoutManager(LinearLayoutManager(activity))
Исправился

2020-08-27 20:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/adapters/PersonListAdapter.kt
> +            override val containerView: View)
Исправил

2020-08-28 04:48 UTC, RomanMDev approved these changes

2020-08-28 04:50 UTC, merged