Перевод на Kotlin подробной информации о контакте
yuhnin-m/Android-Lessons pull request #14
Opened 2020-09-01 10:19 UTC by yuhnin-m

Переписаны на Котлин следующие компоненты:
- Фрагмент
- Презентер
- Вью
- Адаптер
- Мапперы

Исправлены названия переменных в XML разметке.
Помимо этого, устаревший ListView заменен на RecyclerView и заменена жесткое задание строковых значений на запрос из ресурсов

2020-09-01 11:49 UTC, RomanMDev requested changes

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/mapper/ContactModelDataMapper.kt
> +        contact.apply {
`apply` тут неуместна https://kotlinlang.org/docs/reference/scope-functions.html#functions

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/mapper/PersonModelAdvancedDataMapper.kt
> +        person.apply {
заменить `apply`

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +    fun requestContactsByPerson(personId: @NonNull String) {
Лишняя аннотация

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                            .map { contactList: List<Contact> -> Pair(person, contactList) }
`Pair` можно создать инфиксной функцией `to()`.  
`.map { contactList-> person to contactList}`

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                        { personModelAdvancedListPair: Pair<Person, List<Contact>> ->
Все же не стоит постоянно так писать, когда можно обойтись it. Либо тип не указывай. Хоть это и вкусовщина.

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                        { personModelAdvancedListPair: Pair<Person, List<Contact>> ->
`Pair` благодаря котлиновскому Destructuring Declarations (https://kotlinlang.org/docs/reference/multi-declarations.html) в лямбде можно разворачивать:
` { (person, contacts) ->
  person?.let {
                                viewState.fetchContactDetails(personModelDataMapper.transform(it))
                            }
          contacts?.let {
                                viewState.fetchContactsInfo(contactModelDataMapper.transform(it))
                            }`

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +    fun checkBirthdayReminderEnabled(personId: @NonNull String?): Boolean {
Лишняя аннотация

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +    fun birthdayReminderEnable(person: @NonNull PersonModelAdvanced?): Boolean {
Лишняя аннотация

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +    fun birthdayReminderEnable(person: @NonNull PersonModelAdvanced?): Boolean {
Джавовая аннотация nonnull с котлиновским nullable-типом. Надо определиться как в итоге нужно

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +        return reminderInteractor.setBirthdayReminder(person!!.id, person.fullName, person.stringBirthday)
Обработать nullable-переменную, если конечно она все таки nullable

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +    fun birthdayReminderDisable(personId: @NonNull String?): Boolean {
Аннотация

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +
Лишняя строка

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +    override fun onDetach() {
методы жизненного цикла лучше писать в порядке их вызова

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +            val reminderEnabled = personDetailsPresenter.checkBirthdayReminderEnabled(person!!.id)
`!!`

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +            Log.d(LOG_TAG, "����������� " + if (reminderEnabled) " ��������" else " ���������")
Опять что-то с кодировкой

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        togglebtnRemindBirthday?.setOnCheckedChangeListener(this)
Почему view nullable типом сделал?

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +            person?.let {
person же nonnul указан

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        recyclerviewContacts?.let {
view nullable

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        progressbarLoadDetails?.isVisible = true;
view nullable

2020-09-01 11:49 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        progressbarLoadDetails?.isVisible = false;
view nullable

2020-09-01 11:53 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        togglebtnRemindBirthday?.setOnCheckedChangeListener(this)
По поводу nullable. У меня пока еще глаз не цепляется за эти знаки вопроса. Исправлю!

2020-09-02 10:52 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                        { personModelAdvancedListPair: Pair<Person, List<Contact>> ->
Да, так гораздо красивее. Исправил

2020-09-02 10:52 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                            .map { contactList: List<Contact> -> Pair(person, contactList) }
удобная функция, буду использовать

2020-09-02 11:37 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/repositories/PersonListRepositoryFromSystem.kt
>              cursor?.let {
Для наследников closeable можно использвать функцию `use`, которая сама закроет источник https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html

Можно не править

2020-09-02 11:37 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                            contacts?.let {
contacts указан как nonnul. Без `let`

2020-09-02 11:37 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        togglebtnRemindBirthday.let {
let не нужен. Если хотел сделать скоуп, то подходит или with, или run

2020-09-02 11:37 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +            person.let {
let не нужен

2020-09-02 11:37 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        recyclerviewContacts.let {
let не нужен

2020-09-02 11:37 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonDetailsFragment.kt
> +        progressbarLoadDetails.isVisible = false;
`;`- здесь и выше удалить

2020-09-02 12:32 UTC, RomanMDev approved these changes

2020-09-02 12:35 UTC, merged