Перевод на Kotlin фрагмент задания местоположения контакта
yuhnin-m/Android-Lessons pull request #16
Opened 2020-09-08 04:54 UTC by yuhnin-m

Переписаны на Котлин следующие компоненты:
Фрагмент
Презентер
Вью
Мапперы
Исправлены названия переменных в XML разметке.
Исправлен запрос разрешений на геолокацию, запись в память

2020-09-08 07:17 UTC, RomanMDev requested changes

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/mapper/LocationModelMapper.kt
> +     * ������������� ������ [LocationModel] � ����� [Location]
(╯°□°）╯︵ ┻━┻

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +        try {
такой try обработает только работу билдера. Так и задумано?

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                personDetailsInteractor.loadPersonDetails(personId).flowOn(Dispatchers.IO).flatMapMerge { personDetails ->
цепочку столбиком

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                    viewState.fetchContactDetails(personModelDataMapper.transform(personDetails))
Здесь и ниже with. Иногда при повторении переменной использование with (run и т.д) делает код только менее удобочитаемым и можно оставлять как есть, но тут прямо так и напрашивается

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +        } catch (e: Exception) {
Для обработки try catch конструкций в котлине можно во многих случаях использовать `runCatching` https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/run-catching.html

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonMapPresenter.kt
> +
строка

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonMapPresenter.kt
> +        try {
Здесь и далее точно нужен try билдера?

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonMapPresenter.kt
> +                personLocationInteractor.loadLocationByPerson(personId).flowOn(Dispatchers.IO)
в цепочку

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonMapPresenter.kt
> +                                LocationModelMapper().transformEntityToModel(location)
мапперы надо инжектить. Маппинг можно в цепочке сделать

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonMapPresenter.kt
> +
строка

2020-09-08 07:17 UTC, ghost commented on library/src/main/java/com/a65apps/library/receivers/BirthdayReminderReceiver.kt
> +
строка

2020-09-08 07:17 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/repositories/PersonDetailsRepositoryFromSystem.kt
> +import java.util.*
Здесь и по всему коду импорты желательно указывать явно, без звездочек. Settings->Code style-> Kotlin->Import

2020-09-08 07:17 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/repositories/PersonDetailsRepositoryFromSystem.kt
> +                ContactsContract.CommonDataKinds.Phone.CONTACT_ID + " = " + personId,
Строка с аргументам ("$ContactsContract.CommonDataKinds.Phone.CONTACT_ID = ")

2020-09-08 07:17 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/repositories/PersonLocationRepositoryFromDb.kt
> +            emit(LocationModelMapper().transformModelToEntity(locationModel = personLocation))
здесь и далее inject маппер

2020-09-08 07:17 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/activities/MainActivity.java
> +        permissionStatus += ContextCompat.checkSelfPermission(this, Manifest.permission.INTERNET);
https://developer.android.com/guide/topics/permissions/overview#normal-dangerous
Не для всех пермишенов нужно "ручное" разрешение

2020-09-08 07:17 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/activities/MainActivity.java
> +        if (isNeedRequestPermissions) {
флаг перезаписывается. Ну и посмотреть какие пермишены к какой категории относятся

2020-09-08 10:27 UTC, RomanMDev requested changes

2020-09-08 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +
Строка

2020-09-08 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +            this.googleMap = gMap
ссылку лучше сделать nullable и очищать,т.к. lateinit может свалиться

2020-09-08 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +class PersonMapsFragment() : MvpAppCompatFragment(), PersonMapView, OnMapReadyCallback {
Лишние скобки

2020-09-08 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +    var onPersonSetLocation: OnPersonSetLocation? = null
тут и выше private

2020-09-08 10:27 UTC, ghost commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +        @JvmStatic
Точно нужна аннотация? Можно обращаться через companion объект из java

2020-09-08 10:27 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +        fun newInstance(personId: String): PersonMapsFragment {
fun newInstance(personId: String) = PersonMapsFragment().apply { 
            arguments = bundleOf(Constants.KEY_PERSON_ID to personId)
        }

2020-09-08 10:27 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +        return inflater.inflate(R.layout.fragment_person_maps, container, false)
Можно лайаут задавать в конструкторе фрагмента https://developer.android.com/reference/androidx/fragment/app/Fragment#summary

2020-09-08 10:27 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        super.onViewCreated(view, savedInstanceState)
зачем переносишь везде?

2020-09-08 10:27 UTC, RomanMDev commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        @JvmStatic
не нужна

2020-09-08 10:28 UTC, RomanMDev commented
Ctrl+alt+L, Ctrl+Alt+O

2020-09-08 12:45 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/activities/MainActivity.java
> +        if (isNeedRequestPermissions) {
Мысль была такая: если необходимо хоть одно разрешение, то флаг встане в `true`. По идее логическое ИЛИ должно подойти для реализации такого поведения флага.

2020-09-08 12:53 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        super.onViewCreated(view, savedInstanceState)
Не понял, что переношу?

2020-09-08 13:03 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +        return inflater.inflate(R.layout.fragment_person_maps, container, false)
Если фрагмент наследуется от `Fragment`, то да, так получается (я так сделал в `PermissionInfoFragment`). Но этот фрагмент от `MvpAppCompatFragment`, а в нем нет конструктора, который принимает resId

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +        try {
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                personDetailsInteractor.loadPersonDetails(personId).flowOn(Dispatchers.IO).flatMapMerge { personDetails ->
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                    viewState.fetchContactDetails(personModelDataMapper.transform(personDetails))
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +        } catch (e: Exception) {
ок

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/repositories/PersonDetailsRepositoryFromSystem.kt
> +import java.util.*
исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/repositories/PersonDetailsRepositoryFromSystem.kt
> +                ContactsContract.CommonDataKinds.Phone.CONTACT_ID + " = " + personId,
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/repositories/PersonLocationRepositoryFromDb.kt
> +            emit(LocationModelMapper().transformModelToEntity(locationModel = personLocation))
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/activities/MainActivity.java
> +        permissionStatus += ContextCompat.checkSelfPermission(this, Manifest.permission.INTERNET);
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +            this.googleMap = gMap
Поправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +class PersonMapsFragment() : MvpAppCompatFragment(), PersonMapView, OnMapReadyCallback {
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +    var onPersonSetLocation: OnPersonSetLocation? = null
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +        @JvmStatic
Исправил

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonMapsFragment.kt
> +        fun newInstance(personId: String): PersonMapsFragment {
Поправил, красиво

2020-09-08 13:34 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/ui/fragments/PersonListFragment.kt
> +        @JvmStatic
Исправил

2020-09-08 13:36 UTC, yuhnin-m commented on library/src/main/java/com/a65apps/library/mapper/LocationModelMapper.kt
> +     * ������������� ������ [LocationModel] � ����� [Location]
Надеюсь наконец-то победил кодировку

2020-09-09 10:29 UTC, ghost commented on library/src/main/java/com/a65apps/library/presenters/PersonDetailsPresenter.kt
> +                    .flatMapMerge { personDetails ->
main thread
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/flow-on.html

2020-09-09 10:47 UTC, RomanMDev approved these changes

2020-09-09 10:47 UTC, merged